### PR TITLE
Chore: add w3cids, fix http:// urls

### LINKED ISSUE #314: Specberus errors happen during spec-prod
```
  Specberus Errors:
    Wrong syntax for Latest Version link.
      {
        name: 'headers.dl',
        section: 'front-matter',
        rule: 'docIDLatestVersion'
      }
    Missing `data-editor-id` attribute for editor(s): Gary Kacmarcik (Google)
         , Travis Leithead (Microsoft)
         .
      { name: 'headers.dl', section: 'front-matter', rule: 'editorSection' }
  
  Details: https://labs.w3.org/echidna/api/status?id=e97e416c-5226-491e-839f-c0611d543098
  💥 Echidna publish has failed.
```

@marcoscaceres wanna take a look?

### PR DESCRIPTION
**Pull request by marcoscaceres**
Closes #314

### CODE REVIEW

**Review by garykac — APPROVED** [review]

**Review by saschanaz — APPROVED** [review]
TIL `from biblio`

**Comment by marcoscaceres** [comment]
Yeah, Tab added it a few months ago to make the previous stuff a bit easier to manage. It's very handy!

**Comment by marcoscaceres** [comment]
There is a bit more magic to be done over on the gh-pages branch it seems. I think one of you might need to run the build script + bikeshed and do a manual `git merge` on gh-pages to get it all in sync, then auto-pub should start working (the build is failing because of untracked files). 

I'd do it, but I'm not very familiar with the structure of the repo - so I'm worried about doing it wrong. However, any other issues I can try to help!

**Comment by saschanaz** [comment]
I don't think `.cache` will be tracked after merge? 🤔

**Pull request merged**
