### PR TITLE
Add text around dispatching mouseenter/leave/out/over when an element

### PR DESCRIPTION
**Pull request by dtapuska**
or possibly its descendants move.

Fixes issue 154

### CODE REVIEW

**Comment by RByers** [comment]
That's issue #154 (to get the cross-reference).

**Comment by RByers** [comment]
@garykac any thoughts?

**Comment by garykac** [comment]
@dtapuska Do you know how to fix the IPR issues for your account?

**Comment by chaals** [comment]
@garykac go ahead and merge if you like it - it is IPR clean. I will follow up the IPR issues (the simple way is to get your AC rep to add you to the working group, there are a couple of other possibilities).

**Comment by dtapuska** [comment]
@garykac I had fixed the IPR issues after I initially submitted it. Thanks for merging it.

**Comment by chaals** [comment]
(confirmed that the system now believes @dtapuska has done the IPR approval dance - thanks)

**Pull request merged**
