### PR TITLE
Update event-types.txt: Not all wheel events are cancelable.

### PR DESCRIPTION
**Pull request by sahel-sh**

### CODE REVIEW

**Comment by domenic** [comment]
Since this is in a note, it has no normative impact, and can't be used as a basis for changing browser behavior.

**Comment by RByers** [comment]
+1 to the principle here.  I think we want something closer to what we did in TouchEvents - update the [event definition](http://w3c.github.io/uievents/#event-type-wheel) to say cancelability [varies](https://w3c.github.io/touch-events/#list-of-touchevent-types) with a link to [some normative text with "MAY"](https://w3c.github.io/touch-events/#cancelability).  @domenic, WDYT - is the Touch Events example good enough?

**Comment by RByers** [comment]
Note this PR aims to fix #170

**Comment by domenic** [comment]
Yeah, it's reasonable, apart from the whole no processing model business which is out of scope for solving here.

**Comment by dontcallmedom** [comment]
Marked as non substantive for IPR from ash-nazg.

**Pull request merged**
