### PR TITLE
Setup spec-prod CI

### PR DESCRIPTION
**Pull request by saschanaz**
This requires adding `main` branch as the default one instead of the current `gh-pages`. Demo: https://github.com/saschanaz/uievents/tree/gh-pages

***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Mar 20, 2021, 10:09 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.

:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Fuievents%2F7f9718d1cb77c1f0b4ccb20c59cda8edb0f7d6fd%2Findex.html%3FisPreview%3Dtrue)

```
📡 HTTP Error 404: https://rawcdn.githack.com/w3c/uievents/7f9718d1cb77c1f0b4ccb20c59cda8edb0f7d6fd/index.html
```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/uievents%23297.)._
</details>

### CODE REVIEW

**Comment by foolip** [comment]
This will fix the remaining missing `{}` default values in IDL constructors, right?

**Comment by saschanaz** [comment]
Yup, see: https://saschanaz.github.io/uievents/#idl-index

**Review by garykac — APPROVED** [review]

**Comment by foolip** [comment]
It looks like this still did not work, because the branch name is `main` instead of `gh-pages` in one place.

**Comment by foolip** [comment]
Ah, the intention is to now add a `main` branch.

**Comment by saschanaz** [comment]
The spec page now just shows README because of the branch issue, @garykac could you add `main` branch and set it as the default? Thanks!

**Comment by garykac** [comment]
Done. Please let me know if there's something else that needs to be updated.

**Comment by garykac** [comment]
A copied all the branch protections rules from gh-pages to main.

**Comment by saschanaz** [comment]
CI still thinks the default branch is `gh-pages`, I think adding a new commit will fix it. Probably by merging https://github.com/w3c/uievents/pull/298 ?

**Comment by garykac** [comment]
I merged that PR into gh-pages to see if that helps CI.

I'll make the same change to the main branch as well.

**Comment by saschanaz** [comment]
Thanks, I just found that the base branch was still `gh-pages` 😬

**Comment by foolip** [comment]
https://github.com/w3c/uievents/runs/2177478422?check_suite_focus=true ended up not pushing any commit to the `gh-pages` branch.

**Comment by saschanaz** [comment]
Yeah, it found a new file but somehow emitted "Nothing to commit. Skipping deploy." Could this be a regression from [02dada27bc41601266ad6f012488b4e09b28e374](https://github.com/w3c/spec-prod/commit/02dada27bc41601266ad6f012488b4e09b28e374)? cc @sidvishnoi

**Comment by garykac** [comment]
In "Run ***@***.***", the "Deploy to GitHub pages" step still refers
to "gh-pages" in that run. I'm not sure where it's getting that from.

**Comment by saschanaz** [comment]
I think that's expected, as pushes by CI are expected to go to gh-pages.

**Comment by sidvishnoi** [comment]
> Could this be a regression from 02dada27bc41601266ad6f012488b4e09b28e374?
No. That hasn't released yet. Will look into it. I think it crashes (with errors swallowed) when `git log` outputs very large amount of data.

> Re: branch issue
You don't need to change repository's default branch. Instead, you can specify `GH_PAGES_BRANCH: gh-pages-release` and ask GitHub pages to deployed from `gh-pages-release` branch in repository settings. Though, as you've renamed already, you don't need to do that again.

**Comment by saschanaz** [comment]
Thanks Sid as always!

I think having gh-pages and then another gh-pages is just confusing, though 😉

**Comment by saschanaz** [comment]
Hmm, so, in that case maybe `git restore -s 8e36f57~1 index.html` on gh-pages and then running the CI job again would fix it. @garykac could you try this, if you still have time?

**Comment by garykac** [comment]
I restored index.html on gh-pages. I assume that the CI will kick off automatically.

**Comment by saschanaz** [comment]
Okay, now it explicitly fails with `[remote rejected] gh-pages -> gh-pages (protected branch hook declined)`. I think some of the rules should be lifted for the CI bot to work. The status check should be done within the CI, and approval shouldn't be required.

**Comment by garykac** [comment]
Done. The only Branch protection now is the "Require branches to be up to date before merging" check.

**Comment by saschanaz** [comment]
https://github.com/w3c/uievents/commit/42fb5bb86fdaafd00513f13563ce2b04d4ec5d52 🎉

**Comment by garykac** [comment]
Thank you!

**Pull request merged**
