### PR TITLE
Change InputEventInit.data default value to null

### PR DESCRIPTION
**Pull request by pyfisch**
Fixes web-platform-test /uievents/constructors/inputevent-constructor.html, subtest "InputEvent constructor without InputEventInit".

cc @garykac I think you forgot to change this when you made the data field nullable.

### CODE REVIEW

**Comment by adambet3** [comment]
hi

**Comment by foolip** [comment]
Ping @garykac, can this be merged?

**Comment by domenic** [comment]
Another ping!

**Review by saschanaz — APPROVED** [review]
It also matches [the spec phrase](https://w3c.github.io/uievents/#dom-inputevent-inputtype):

>The un-initialized value of this attribute MUST be null.

**Review by garykac — APPROVED** [review]

**Pull request merged**
