### PR TITLE
Remove definitions of MutationEvent and friends

### PR DESCRIPTION
**Pull request by mfreed7**
Please see this WHATWG/dom issue for more details:

https://github.com/whatwg/dom/issues/305#issuecomment-2309207540

Mutation events have now been [disabled for most all users of the Chrome browser](https://chromestatus.com/feature/5083947249172480). While there are still a few sites opted back in to the events via origin trial tokens, those are time limited and we've committed to end-date them as soon as possible. However, it feels appropriate to remove the definition of these deprecated events from the standard at this point.

The following tasks have been completed:

 * [X] Confirmed there are no ReSpec/BikeShed errors or warnings.
 * [X] Modified Web platform tests (link to pull request)

    https://github.com/web-platform-tests/wpt/pull/47727

Implementation commitment:

 * [X] WebKit (https://github.com/WebKit/standards-positions/issues/192)
 * [X] Chromium (https://issues.chromium.org/issues/40268638)
 * [X] Gecko (https://github.com/mozilla/standards-positions/issues/807)

### CODE REVIEW

**Review by domenic — APPROVED** [review]
Hmm, I might have merge permissions on this repository? Let's give it a shot...

**Comment by mfreed7** [comment]
> Hmm, I might have merge permissions on this repository? Let's give it a shot...

Guess you do! Thanks!

**Comment by domenic** [comment]
Hmm it's still appearing in https://w3c.github.io/uievents/ though. I think maybe because there are actually many files in this repo, several of which still mention MutationEvent? https://github.com/search?q=repo%3Aw3c%2Fuievents+mutationevent&type=code

**Comment by mfreed7** [comment]
> Hmm it's still appearing in https://w3c.github.io/uievents/ though. I think maybe because there are actually many files in this repo, several of which still mention MutationEvent? https://github.com/search?q=repo%3Aw3c%2Fuievents+mutationevent&type=code

Weird - I definitely left some [references](https://github.com/search?q=repo%3Aw3c%2Fuievents+mutationevent&type=code) to mutation events there, and I'll put up another PR to remove those. But I'm guessing something else needs to get run to re-publish, since none of my removals seem to be published. E.g. [this section](https://w3c.github.io/uievents/#event-type-DOMAttrModified) doesn't exist in the source, at least that I can see.

**Comment by mfreed7** [comment]
> > Hmm it's still appearing in https://w3c.github.io/uievents/ though. I think maybe because there are actually many files in this repo, several of which still mention MutationEvent? https://github.com/search?q=repo%3Aw3c%2Fuievents+mutationevent&type=code
> 
> Weird - I definitely left some [references](https://github.com/search?q=repo%3Aw3c%2Fuievents+mutationevent&type=code) to mutation events there, and I'll put up another PR to remove those. But I'm guessing something else needs to get run to re-publish, since none of my removals seem to be published. E.g. [this section](https://w3c.github.io/uievents/#event-type-DOMAttrModified) doesn't exist in the source, at least that I can see.

No, that's not necessarily true. I think github search maybe just missed them. I'll put up another PR and let's see what it looks like after that one.

**Comment by mfreed7** [comment]
Ok, https://github.com/w3c/uievents/pull/382. I really don't get how this repo is supposed to be built, because it seems like `build.py` doesn't generate all of the seemingly-generated files, such as `TR.html`. Which is also committed to the repo. Anyway, LMK if that looks better!

**Comment by garykac** [comment]
The build script only generates the .bs files from the .txt files. The final .html files are generated by an auto-publish process, so they are not checked in.

The files in the split directory were an experiment from earlier this year that are not active. I will be removing them.

**Pull request merged**
